// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PlayerMessg.proto

package protoparse

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vec struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vec) Reset()         { *m = Vec{} }
func (m *Vec) String() string { return proto.CompactTextString(m) }
func (*Vec) ProtoMessage()    {}
func (*Vec) Descriptor() ([]byte, []int) {
	return fileDescriptor_e003d5724b5ad384, []int{0}
}

func (m *Vec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vec.Unmarshal(m, b)
}
func (m *Vec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vec.Marshal(b, m, deterministic)
}
func (m *Vec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vec.Merge(m, src)
}
func (m *Vec) XXX_Size() int {
	return xxx_messageInfo_Vec.Size(m)
}
func (m *Vec) XXX_DiscardUnknown() {
	xxx_messageInfo_Vec.DiscardUnknown(m)
}

var xxx_messageInfo_Vec proto.InternalMessageInfo

func (m *Vec) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vec) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PlayerAction struct {
	ChanCode             string   `protobuf:"bytes,1,opt,name=ChanCode,proto3" json:"ChanCode,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction) Reset()         { *m = PlayerAction{} }
func (m *PlayerAction) String() string { return proto.CompactTextString(m) }
func (*PlayerAction) ProtoMessage()    {}
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e003d5724b5ad384, []int{1}
}

func (m *PlayerAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction.Unmarshal(m, b)
}
func (m *PlayerAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction.Marshal(b, m, deterministic)
}
func (m *PlayerAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction.Merge(m, src)
}
func (m *PlayerAction) XXX_Size() int {
	return xxx_messageInfo_PlayerAction.Size(m)
}
func (m *PlayerAction) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction proto.InternalMessageInfo

func (m *PlayerAction) GetChanCode() string {
	if m != nil {
		return m.ChanCode
	}
	return ""
}

func (m *PlayerAction) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ShotAction struct {
	Pos                  *Vec     `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Dir                  *Vec     `protobuf:"bytes,2,opt,name=Dir,proto3" json:"Dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShotAction) Reset()         { *m = ShotAction{} }
func (m *ShotAction) String() string { return proto.CompactTextString(m) }
func (*ShotAction) ProtoMessage()    {}
func (*ShotAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e003d5724b5ad384, []int{2}
}

func (m *ShotAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShotAction.Unmarshal(m, b)
}
func (m *ShotAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShotAction.Marshal(b, m, deterministic)
}
func (m *ShotAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShotAction.Merge(m, src)
}
func (m *ShotAction) XXX_Size() int {
	return xxx_messageInfo_ShotAction.Size(m)
}
func (m *ShotAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ShotAction.DiscardUnknown(m)
}

var xxx_messageInfo_ShotAction proto.InternalMessageInfo

func (m *ShotAction) GetPos() *Vec {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *ShotAction) GetDir() *Vec {
	if m != nil {
		return m.Dir
	}
	return nil
}

type UpdateView struct {
	Enemys               []*Vec   `protobuf:"bytes,1,rep,name=Enemys,proto3" json:"Enemys,omitempty"`
	Shots                []*Vec   `protobuf:"bytes,2,rep,name=Shots,proto3" json:"Shots,omitempty"`
	Life                 int32    `protobuf:"varint,3,opt,name=Life,proto3" json:"Life,omitempty"`
	Pos                  *Vec     `protobuf:"bytes,4,opt,name=Pos,proto3" json:"Pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateView) Reset()         { *m = UpdateView{} }
func (m *UpdateView) String() string { return proto.CompactTextString(m) }
func (*UpdateView) ProtoMessage()    {}
func (*UpdateView) Descriptor() ([]byte, []int) {
	return fileDescriptor_e003d5724b5ad384, []int{3}
}

func (m *UpdateView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateView.Unmarshal(m, b)
}
func (m *UpdateView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateView.Marshal(b, m, deterministic)
}
func (m *UpdateView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateView.Merge(m, src)
}
func (m *UpdateView) XXX_Size() int {
	return xxx_messageInfo_UpdateView.Size(m)
}
func (m *UpdateView) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateView.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateView proto.InternalMessageInfo

func (m *UpdateView) GetEnemys() []*Vec {
	if m != nil {
		return m.Enemys
	}
	return nil
}

func (m *UpdateView) GetShots() []*Vec {
	if m != nil {
		return m.Shots
	}
	return nil
}

func (m *UpdateView) GetLife() int32 {
	if m != nil {
		return m.Life
	}
	return 0
}

func (m *UpdateView) GetPos() *Vec {
	if m != nil {
		return m.Pos
	}
	return nil
}

func init() {
	proto.RegisterType((*Vec)(nil), "protoparse.Vec")
	proto.RegisterType((*PlayerAction)(nil), "protoparse.PlayerAction")
	proto.RegisterType((*ShotAction)(nil), "protoparse.ShotAction")
	proto.RegisterType((*UpdateView)(nil), "protoparse.UpdateView")
}

func init() { proto.RegisterFile("PlayerMessg.proto", fileDescriptor_e003d5724b5ad384) }

var fileDescriptor_e003d5724b5ad384 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0x49, 0xb6, 0x2d, 0xf6, 0x59, 0x14, 0xdf, 0x69, 0xf1, 0xd4, 0x06, 0xc4, 0x9e, 0xf6,
	0xa0, 0x37, 0x6f, 0xd2, 0x78, 0x28, 0x28, 0x94, 0x88, 0x7b, 0x8f, 0xdb, 0xa7, 0x0d, 0xe8, 0x66,
	0x49, 0x02, 0x36, 0xbf, 0xc3, 0x3f, 0x2c, 0xc9, 0x56, 0xbd, 0x6c, 0x4f, 0xc9, 0xbc, 0x99, 0x6f,
	0x18, 0xb8, 0xd8, 0x7c, 0xe8, 0x48, 0xee, 0x89, 0xbc, 0x7f, 0xaf, 0x3a, 0x67, 0x83, 0x45, 0xc8,
	0x4f, 0xa7, 0x9d, 0x27, 0xb1, 0x80, 0xa2, 0xa6, 0x06, 0x67, 0xc0, 0xf6, 0x25, 0x9b, 0xb3, 0x25,
	0x57, 0x6c, 0x9f, 0x54, 0x2c, 0x79, 0xaf, 0xa2, 0xb8, 0x83, 0x59, 0xdf, 0x71, 0xdf, 0x04, 0x63,
	0x5b, 0xbc, 0x84, 0x93, 0xd5, 0x4e, 0xb7, 0x2b, 0xbb, 0xa5, 0x8c, 0x4c, 0xd5, 0x9f, 0xc6, 0x33,
	0xe0, 0x6b, 0x99, 0xd1, 0xa9, 0xe2, 0x6b, 0x29, 0x14, 0xc0, 0xf3, 0xce, 0x86, 0x03, 0xb9, 0x80,
	0x62, 0x63, 0x7d, 0x86, 0x4e, 0x6f, 0xce, 0xab, 0xff, 0x19, 0x55, 0x4d, 0x8d, 0x4a, 0x5e, 0x8a,
	0x48, 0xe3, 0x72, 0xc3, 0x50, 0x44, 0x1a, 0x27, 0xbe, 0x19, 0xc0, 0x4b, 0xb7, 0xd5, 0x81, 0x6a,
	0x43, 0x5f, 0x78, 0x0d, 0x93, 0x87, 0x96, 0x3e, 0x63, 0xea, 0x2d, 0x86, 0xa0, 0x83, 0x8d, 0x57,
	0x30, 0x4e, 0x5b, 0x7c, 0xc9, 0x87, 0x73, 0xbd, 0x8b, 0x08, 0xa3, 0x47, 0xf3, 0x46, 0x65, 0x31,
	0x67, 0xcb, 0xb1, 0xca, 0xff, 0xdf, 0xe1, 0xa3, 0xe3, 0xc3, 0x5f, 0x27, 0xf9, 0x78, 0xfb, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x55, 0x18, 0xd5, 0x23, 0x70, 0x01, 0x00, 0x00,
}
